function getInfo() {
	window.numberOfQuestions = 	10;
	window.currentSlide = 		0;
	window.currentScore = 		0;
	window.title = 				"SUPER SMASH BROS TRIVIA";
	window.questions = [		"WHO CREATED SUPER SMASH BROS?", 
								"WHICH YEAR WAS THE FIRST SUPER SMASH BROS. GAME RELEASED?",
								"HOW MANY SUPER SMASH BROS GAMES ARE THERE? (WII U AND 3DS ENTRIES SEPARATE)", 
								"WHICH SUPER SMASH BROS. GAME HAS SOLD THE MOST COPIES?", 
								"WHICH OF THESE FRANCHISES DOES NOT HAVE A FIGHTER IN ANY SMASH BROS. GAME?",
								"WHICH OF THESE POKEMON IS IN SUPER SMASH BROS. MELEE?", 
								"WHICH CONSOLE WAS SUPER SMASH BROS. BRAWL RELEASED FOR?",
								"WHICH OF THESE GAME MODES IS EXCLUSIVE TO SUPER SMASH BROS. FOR 3DS?", 
								"WHO WAS THE FINAL DLC CHARACTER ANNOUNCED FOR SUPER SMASH BROS. FOR 3DS AND WII U?", 
								"IN SUPER SMASH BROS. ULTIMATE'S WORLD OF LIGHT, WHICH CHARACTER DOES THE PLAYER START WITH?" ];
	window.correctAnswer = [ 	"A", "C", "B", "D", "B", "E", "E", "A", "C", "D" ]; 
	window.answerA = [ 			"MASAHIRO SAKURAI", 
								"1492", 
								"5", 
								"SUPER SMASH BROS. MELEE", 
								"METAL GEAR",
								"GATOMON",
								"PLAYSTATION 2",
								"SMASH RUN",
								"PIRANHA PLANT",
								"MARIO" ];	
	window.answerB = [ 			"SHIGERU MIYAMOTO", 
								"1998", 
								"6", 
								"SUPER SMASH BROS. BRAWL", 
								"CHIBI-ROBO!", 
								"BLAZIKEN",
								"NINTENDO DS",
								"SMASH TOUR",
								"GOKU",
								"THEIR MII" ];					
	window.answerC = [ 			"HATSUNE MIKU",  
								"1999", 
								"7", 
								"SUPER SMASH BROS. FOR WII U", 
								"THE LEGEND OF ZELDA",
								"LUCARIO", 
								"XBOX 360",
								"HOME RUN CONTEST",
								"BAYONETTA",
								"PIKACHU" ];					
	window.answerD = [ 			"BILL TRINEN", 
								"2000", 
								"8",  
								"SUPER SMASH BROS. ULTIMATE", 
								"FIRE EMBLEM",
								"RAICHU",
								"NINTENDO GAMESPHERE",
								"SUBSPACE EMISSARY",
								"CORRIN",
								"KIRBY" ];									
	window.answerE = [ 			"REGGIE FILS-AMIE", 
								"2001", 
								"42", 
								"SUPER SMASH BROS. CRUSADE", 
								"STREET FIGHTER",
								"MEWTWO",
								"NINTENDO WII",
								"CITY TRIAL",
								"CLOUD",
								"SANS" ];
	window.response = [ 		"MASAHIRO SAKURAI IS THE CREATOR AND LEAD DEVELOPER OF SUPER SMASH BROS.", 
								"THE FIRST SMASH GAME, SIMPLY TITLED 'SUPER SMASH BROS.', WAS RELEASED FOR THE NINTENDO 64 IN JAPAN ON JAN. 21, 1999. NORTH AMERICAN AND EUROPEAN RELEASES CAME LATER THAT YEAR.", 
								"COUNTING SMASH FOR 3DS AND WII U AS SEPARATE GAMES, THERE ARE CURRENTLY 6 GAMES IN THE SUPER SMASH BROS. SERIES.", 
								"SUPER SMASH BROS. ULTIMATE HAS RECENTLY SURPASSED BRAWL FOR MOST COPIES SOLD WITH 13.81 MILLION AND COUNTING.", 
								"CHIBI-ROBO! DOES NOT HAVE A FIGHTER IN SMASH BROS., DESPITE SOME DEMAND FROM FANS.",
								"MEWTWO CAN BE UNLOCKED IN SUPER SMASH BROS. MELEE BY PLAYING 20 HOURS OF VS. MATCHES.", 
								"SMASH BROS. BRAWL WAS RELEASED FOR THE NINTENDO WII ON JANUARY 31, 2008 IN JAPAN. NORTH AMERICAN AND EUROPEAN RELEASES CAME WITHIN THE NEXT 2 MONTHS.", 
								"SMASH RUN, A GAMEMODE PARTIALLY INSPIRED BY KIRBY AIR RIDE'S CITY TRIAL, IS EXCLUSIVE TO SUPER SMASH BROS. FOR 3DS.", 
								"THE FINAL DLC CHARACTER ANNOUNCED FOR SUPER SMASH BROS. FOR 3DS AND WII U WAS BAYONETTA, THOUGH SHE RELEASED AT THE SAME TIME AS CORRIN, ANOTHER DLC CHARACTER.", 
								"IN WORLD OF LIGHT, THE ONLY CHARACTER AVAILABLE AT THE START OF THE GAME IS KIRBY, WHO IS ANOTHER OF MASAHIRO SAKURAI'S CREATIONS." ];
							
}
						